name: monet-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9
  #
  # core
  - cartopy
  - dask
  - matplotlib
  - netcdf4
  - pydecorate
  - pandas
  - seaborn
  - xarray
  #
  # optional
  - pyresample
  - xesmf # non-Windows only!
  #
  # test/dev
  - ipykernel
  - ipython
  - pytest
