name: monet-docs
channels:
  - conda-forge
  - nodefaults
  - pkgs/main
dependencies:
  - python==3.7
  - cartopy
  - dask
  - ipykernel
  - ipython
  - nbsphinx
  - numpy
  - numpydoc
  - pandas>=1.0
  - seaborn
  - sphinx>=2.3
  - sphinx_rtd_theme>=0.4
