name: monet
channels:
  - conda-forge
dependencies:
  - python==3.7
  - pip:
    - numpy
    - cartopy
    - dask
    - xarray
    - seaborn
    - python-stratify
    - pydecorate
    - xesmf
    - pyresample
    - sphinxcontrib
    - sphinx
