name: monet-docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9
  - ipykernel
  - ipython
  #
  # core
  - cartopy
  - dask
  - matplotlib
  - netcdf4
  - numpy
  - pandas>=1.0
  - pydecorate
  - seaborn
  - xarray
  #
  # optional
  - pyresample
  #
  # docs
  - nbsphinx
  - sphinx=4.*
  - sphinx-autobuild
  - sphinx-autosummary-accessors
  - sphinx_rtd_theme>=0.4
  #
  - pip>=21.1
  - pip:
      - "-e ../"
